export interface ContaReceber {
  id_ctarec: number;
  id_empresa?: string;
  documento: string;
  historico: string | null;
  dt_emissao: string;
  dt_vencto: string;
  dt_baixa: string | null;
  hr_baixa: string | null;
  vlr_ctarec: number;
  vlr_receb: number | null;
  tip_ctarec: string;
  id_portador: number | null;
  id_cliente: number;
  cliente_nome: string | null;
  cliente_status: string | null;
  cliente_telefone: string | null;
  cliente_email: string | null;
  id_venda: number | null;
  id_vendedor: number | null;
  vendedor_codigo: string | number | null;
  vendedor_nome: string | null;
  vendedor_apelido: string | null;
  vendedor_status: string | null;
  vendedor_telefone: string | null;
  vendedor_email: string | null;
  id_conta: number | null;
  id_ctapla_origem: number | null;
  id_tipo_cliente: number | null;
  inv_referencia: string | null;
  dt_vencto_orig: string | null;
  nsu_cartao: string | null;
  observacao: string | null;
  txid_qrcode_pix: string | null;
  id_bank_account: number | null;
  ignora_concil_cartao: string | null;
  id_conversao: number | null;
  receb_aut: number | null;
  id_debx: number | null;
  id_cartao_operadora: number | null;
  whatsapp_status: string | null;
  whatsapp_ultimo_envio_em: string | null;
  whatsapp_total_envios: number | null;
  whatsapp_ultimo_erro: string | null;
  whatsapp_ultimo_tipo: string | null;
  whatsapp_ultimo_envio_id: number | null;
  whatsapp_primeiro_envio_em: string | null;
  whatsapp_ultimo_reenvio_em: string | null;
  whatsapp_total_reenvios: number | null;
  whatsapp_status_exibicao: string | null;
  sincronizado_em: string | null;
}
